import { lifeEvents } from "../../data/account/foundation.ts";
import type { Recommendation, RoadmapInput, RoadmapOutput } from "../../data/account/types.ts";

const catalog: Recommendation[] = [
  { id: "define-priority", title: "Define tu prioridad principal", description: "Elige el área que necesita atención primero para mantener tu camino manejable.", stage: "LLEGA", priority: 1, category: "GENERAL", status: "NOW", sourceType: "EVOLUSA_GUIDE", requiresProfessional: false, actionType: "COMPLETE_TASK", reason: "Da contexto al resto del Roadmap." },
  { id: "id-and-license", title: "Tramita tu identificación", description: "Confirma con el DMV de tu estado los requisitos para licencia de conducir o ID estatal, y con la SSA si corresponde un Seguro Social.", stage: "LLEGA", priority: 2, category: "DOCUMENTS", status: "NOW", sourceType: "OFFICIAL", requiresProfessional: false, actionType: "READ", reason: "Documentos aparece entre tus necesidades o etapa Llega." },
  { id: "employment-checklist", title: "Organiza tu nueva etapa laboral", description: "Revisa documentos de empleo, presupuesto y beneficios que necesitas comprender.", stage: "ESTABLECETE", priority: 1, category: "WORK", status: "NOW", sourceType: "EVOLUSA_GUIDE", requiresProfessional: false, actionType: "PLAN", reason: "Seleccionaste trabajo o informaste un cambio laboral." },
  { id: "financial-basics", title: "Ordena tus finanzas básicas", description: "Crea una lista simple de ingresos, gastos recurrentes y próximos compromisos.", stage: "ESTABLECETE", priority: 2, category: "FINANCES", status: "NOW", sourceType: "EVOLUSA_GUIDE", requiresProfessional: false, actionType: "COMPLETE_TASK", reason: "Finanzas aparece entre tus necesidades." },
  { id: "official-documents", title: "Consulta la fuente oficial correspondiente", description: "Usa información gubernamental oficial para requisitos y trámites específicos.", stage: "ESTABLECETE", priority: 2, category: "DOCUMENTS", status: "UPCOMING", sourceType: "OFFICIAL", requiresProfessional: false, actionType: "READ", reason: "Seleccionaste ayuda para organizar documentos." },
  { id: "housing-search", title: "Organiza tu búsqueda de vivienda", description: "Define presupuesto, zona y los requisitos típicos de alquiler (historial, referencias, depósito) antes de buscar.", stage: "ESTABLECETE", priority: 2, category: "HOUSING", status: "NOW", sourceType: "EVOLUSA_GUIDE", requiresProfessional: false, actionType: "PLAN", reason: "Vivienda aparece entre tus necesidades o eventos." },
  { id: "home-buying-readiness", title: "Evalúa tu preparación para comprar casa", description: "Revisa tu crédito, ahorro para el enganche y una pre-aprobación con un prestamista autorizado.", stage: "CRECE", priority: 2, category: "HOUSING", status: "LATER", sourceType: "PROFESSIONAL", requiresProfessional: true, actionType: "CONTACT_PROFESSIONAL", reason: "Indicaste interés en comprar casa." },
  { id: "vehicle-basics", title: "Prepárate para tener un vehículo", description: "Compara comprar o financiar, y confirma el seguro obligatorio con un agente autorizado y los requisitos de licencia de tu estado antes de decidir.", stage: "ESTABLECETE", priority: 2, category: "TRANSPORT", status: "UPCOMING", sourceType: "EVOLUSA_GUIDE", requiresProfessional: false, actionType: "PLAN", reason: "Transporte aparece entre tus necesidades." },
  { id: "credit-building", title: "Empieza a construir tu historial crediticio", description: "Una cuenta bancaria, una tarjeta con depósito de garantía (secured card) y pagos puntuales son los pasos habituales para empezar.", stage: "ESTABLECETE", priority: 3, category: "CREDIT", status: "UPCOMING", sourceType: "EVOLUSA_GUIDE", requiresProfessional: false, actionType: "PLAN", reason: "Crédito aparece entre tus necesidades." },
  { id: "insurance-basics", title: "Revisa tus seguros esenciales", description: "Salud, auto y renta u hogar son las coberturas más comunes al establecerte; confirma requisitos y opciones con un agente autorizado.", stage: "ESTABLECETE", priority: 2, category: "INSURANCE", status: "UPCOMING", sourceType: "PROFESSIONAL", requiresProfessional: true, actionType: "CONTACT_PROFESSIONAL", reason: "Seguros aparece entre tus necesidades." },
  { id: "english-practice", title: "Sigue mejorando tu inglés", description: "Busca cursos gratuitos o de bajo costo en un community college o biblioteca pública cercana según tu nivel actual.", stage: "ESTABLECETE", priority: 3, category: "ENGLISH", status: "LATER", sourceType: "EVOLUSA_GUIDE", requiresProfessional: false, actionType: "READ", reason: "Seleccionaste mejorar tu inglés." },
  { id: "education-pathways", title: "Explora tus opciones educativas", description: "Revisa validación de estudios previos, GED, community college o certificaciones técnicas según tu meta.", stage: "ESTABLECETE", priority: 3, category: "EDUCATION", status: "UPCOMING", sourceType: "OFFICIAL", requiresProfessional: false, actionType: "READ", reason: "Educación aparece entre tus necesidades." },
  { id: "family-support", title: "Conecta a tu familia con recursos locales", description: "Busca escuelas, atención médica y programas comunitarios cercanos para quienes dependen de ti.", stage: "ESTABLECETE", priority: 4, category: "FAMILY", status: "UPCOMING", sourceType: "EVOLUSA_GUIDE", requiresProfessional: false, actionType: "READ", reason: "Familia aparece entre tus necesidades." },
  { id: "business-readiness", title: "Evalúa tu preparación para emprender", description: "Aclara oferta, cliente, operación y recursos antes de iniciar trámites.", stage: "EMPRENDE", priority: 1, category: "BUSINESS", status: "NOW", sourceType: "EVOLUSA_GUIDE", requiresProfessional: false, actionType: "PLAN", reason: "Quieres iniciar o ya operas un negocio." },
  { id: "business-formation", title: "Registra tu negocio: estructura, EIN y cuenta bancaria", description: "Con apoyo de un profesional autorizado, confirma la estructura legal apropiada (como una LLC), los pasos para solicitar tu EIN ante el IRS y para abrir una cuenta bancaria comercial separada.", stage: "EMPRENDE", priority: 2, category: "BUSINESS", status: "NOW", sourceType: "PROFESSIONAL", requiresProfessional: true, actionType: "CONTACT_PROFESSIONAL", reason: "Quieres formalizar tu negocio." },
  { id: "tax-professional", title: "Identifica apoyo fiscal apropiado", description: "Prepara tus preguntas y confirma credenciales, alcance y jurisdicción del proveedor.", stage: "PROTEGETE", priority: 1, category: "TAX", status: "UPCOMING", sourceType: "PROFESSIONAL", requiresProfessional: true, actionType: "CONTACT_PROFESSIONAL", reason: "Seleccionaste impuestos como necesidad o evento." },
  { id: "marketing-foundation", title: "Fortalece tu presencia comercial", description: "Revisa marca, sitio web, presencia local y seguimiento de oportunidades.", stage: "CRECE", priority: 2, category: "MARKETING", status: "UPCOMING", sourceType: "PROFESSIONAL", requiresProfessional: true, actionType: "CONTACT_PROFESSIONAL", connectHref: "/conexiones/nueva", reason: "Quieres hacer crecer tu negocio." },
  { id: "future-review", title: "Revisa tu progreso y actualiza cambios", description: "Vuelve a evaluar necesidades y eventos para recibir el siguiente paso.", stage: "EVOLUCIONA", priority: 4, category: "GENERAL", status: "LATER", sourceType: "EVOLUSA_GUIDE", requiresProfessional: false, actionType: "PLAN", reason: "Mantiene el ciclo de progreso activo." },
];

export function generateAccountRoadmap(input: RoadmapInput): RoadmapOutput {
  const eventCategories = lifeEvents.filter((event) => input.lifeEventIds.includes(event.id)).map((event) => event.category);
  const categories = new Set([...input.selectedNeeds, ...input.goals.map((goal) => goal.category), ...eventCategories]);
  const relevant = catalog.filter((item) => item.category === "GENERAL" || categories.has(item.category) || (item.category === "BUSINESS" && input.businessStatus !== "NONE") || (item.category === "WORK" && input.employment === "EMPLOYED"));
  const completedIds = new Set(input.completedTaskIds);
  const normalized = relevant.map((item) => completedIds.has(item.id) ? { ...item, status: "COMPLETED" as const } : item);
  const by = (status: Recommendation["status"]) => normalized.filter((item) => item.status === status).sort((a, b) => a.priority - b.priority);
  return { completed: by("COMPLETED"), now: by("NOW").slice(0, 3), upcoming: by("UPCOMING").slice(0, 4), later: by("LATER") };
}
