import Heading from "@/components/ui/Heading";
import ProgressStep from "@/components/ui/ProgressStep";
import ButtonLink from "@/components/ui/ButtonLink";
import Section from "@/components/ui/Section";
import { generateRoadmap } from "@/lib/roadmap/generateRoadmap";

const preview = generateRoadmap({ hasBusiness: "yes", businessRegistered: "yes", hasBusinessBankAccount: "no", hasBookkeeping: "no", hasWebsite: "no", hasGoogleBusiness: "no", primaryPriority: "organize_business" });

export default function RoadmapPreview() {
  return <Section id="roadmap" labelledBy="roadmap-title" className="bg-[var(--brand-navy)] text-white"><div className="grid items-center gap-12 lg:grid-cols-[0.9fr_1.1fr]"><div><Heading id="roadmap-title" eyebrow="EVOLUSA Roadmap" eyebrowClassName="text-[var(--brand-blue-on-dark)]" className="text-white">Tu nueva vida tiene muchos pasos. Aquí sabes cuál sigue.</Heading><p className="mt-6 text-lg leading-8 text-slate-300">Un cuestionario corto alimenta recomendaciones deterministas y explicables. No utiliza IA ni solicita información sensible innecesaria.</p><ul className="mt-6 space-y-2 text-sm text-slate-300"><li><strong className="text-white">Completado:</strong> fundamentos que indicas haber resuelto.</li><li><strong className="text-white">Ahora:</strong> hasta tres prioridades claras.</li><li><strong className="text-white">Próximamente:</strong> pasos que pueden seguir después.</li></ul><ButtonLink className="mt-8" href="#stage-selector">Comenzar por mi etapa</ButtonLink><p className="mt-5 text-xs leading-5 text-slate-400">Orientación, no asesoría profesional. {preview.disclaimer}</p></div><div className="rounded-[var(--radius-lg)] bg-white p-6 text-[var(--foreground)] shadow-[var(--shadow-md)] sm:p-8"><div className="flex items-center justify-between gap-4"><p className="text-sm font-semibold uppercase tracking-wider text-[var(--brand-blue)]">Tu camino en USA</p><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">Ejemplo</span></div><div className="mt-7 grid gap-7 sm:grid-cols-3"><div><h3 className="mb-4 text-xs font-bold uppercase tracking-wider text-[var(--success)]">Completado</h3><ol className="space-y-5">{preview.completed.slice(0, 1).map((item) => <ProgressStep key={item.id} status="complete" title={item.title} />)}</ol></div><div><h3 className="mb-4 text-xs font-bold uppercase tracking-wider text-[var(--warning)]">Ahora</h3><ol className="space-y-5">{preview.now.slice(0, 2).map((item) => <ProgressStep key={item.id} status="current" title={item.title} />)}</ol></div><div><h3 className="mb-4 text-xs font-bold uppercase tracking-wider text-slate-500">Próximamente</h3><ol className="space-y-5">{preview.upcoming.slice(0, 2).map((item) => <ProgressStep key={item.id} status="upcoming" title={item.title} />)}</ol></div></div></div></div></Section>;
}
