"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { scheduleDays,emptySchedule,type ProfessionalSchedule,type ScheduleDay } from "@/lib/professional-schedule/validation";
import { saveScheduleAction,saveBookingUrlAction } from "@/app/(account)/panel-profesional/agenda/actions";
export default function ProfessionalScheduleForm({initial,bookingUrl}:{initial:ProfessionalSchedule|null;bookingUrl:string|null}){
 const [schedule,setSchedule]=useState(() => initial ?? emptySchedule());const [url,setUrl]=useState(bookingUrl ?? "");
 const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");const [failed,setFailed]=useState(false);const router=useRouter();
 async function save(booking=false){setBusy(true);setNotice("");try{const r=booking?await saveBookingUrlAction(url):await saveScheduleAction(schedule);setNotice(r.message);setFailed(!r.saved);if(r.saved)router.refresh();}catch{setFailed(true);setNotice("No pudimos conectar. Tus cambios siguen aquí.");}finally{setBusy(false);}}
 function dayChange(day:ScheduleDay["day"],fields:Partial<ScheduleDay>){setSchedule(s=>({...s,days:s.days.map(d=>d.day===day?{...d,...fields}:d)}));}
 const field="min-h-12 rounded-xl border border-[var(--border)] bg-white px-3";
 return <div className="space-y-6">
 <section className="rounded-xl border border-[var(--border)] bg-white p-6"><h2 className="text-xl font-bold">Preferencias de disponibilidad</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Estas franjas son orientativas y privadas. No consultan tu calendario, no bloquean horarios y no confirman reservas. Configura también la disponibilidad en tu proveedor de reservas.</p><p className="mt-3 font-semibold">{initial ? initial.status==="ACTIVE" ? "Preferencias activas" : "Disponibilidad pausada" : "Todavía no guardaste tu disponibilidad"}</p>
 <form onSubmit={e=>{e.preventDefault();void save();}} className="mt-5"><fieldset disabled={busy} className="space-y-5 disabled:opacity-60">
 <label className="block font-semibold">Zona horaria<input required maxLength={80} value={schedule.timeZone} onChange={e=>setSchedule(s=>({...s,timeZone:e.target.value}))} className={`${field} mt-2 w-full`}/></label><button type="button" className="min-h-10 text-sm underline" onClick={()=>setSchedule(s=>({...s,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone}))}>Usar zona de mi dispositivo</button>
 <label className="block font-semibold">Estado<select className={`${field} mt-2 w-full`} value={schedule.status} onChange={e=>setSchedule(s=>({...s,status:e.target.value as ProfessionalSchedule["status"]}))}><option value="PAUSED">Disponibilidad pausada</option><option value="ACTIVE">Preferencias activas</option></select></label>
 <div className="space-y-3">{schedule.days.map(d=><div key={d.day} className="flex flex-wrap items-center gap-3 rounded-xl bg-[var(--sky-surface)] p-3"><label className="flex min-w-28 items-center gap-2"><input type="checkbox" checked={d.enabled} onChange={e=>dayChange(d.day,{enabled:e.target.checked})} className="size-5"/>{scheduleDays[d.day]}</label><label className="text-sm">Desde<input type="time" required disabled={!d.enabled} aria-label={`${scheduleDays[d.day]} desde`} value={d.start} onChange={e=>dayChange(d.day,{start:e.target.value})} className={`${field} ml-2`}/></label><label className="text-sm">Hasta<input type="time" required disabled={!d.enabled} aria-label={`${scheduleDays[d.day]} hasta`} value={d.end} onChange={e=>dayChange(d.day,{end:e.target.value})} className={`${field} ml-2`}/></label></div>)}</div>
 <p className="text-sm text-[var(--muted)]">Una franja por día. La hora final debe ser posterior a la inicial; no se admiten franjas que crucen medianoche.</p><button type="submit" className="min-h-12 rounded-full bg-[var(--brand-blue)] px-6 font-bold text-white">{busy?"Guardando…":"Guardar disponibilidad"}</button>
 </fieldset></form></section>
 <section className="rounded-xl border border-[var(--border)] bg-white p-6"><h2 className="text-xl font-bold">Enlace externo de reservas</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Añade el enlace real de tu agenda, por ejemplo Cal.com, Calendly o una página de reservas de Google Calendar. Si ese servicio está configurado para crear una videollamada, él gestionará el enlace. EVOLUSA no crea ni verifica esa llamada.</p><form onSubmit={e=>{e.preventDefault();void save(true);}} className="mt-5 space-y-4"><label className="block font-semibold">Tu enlace de reservas<input type="url" maxLength={500} value={url} disabled={busy} onChange={e=>setUrl(e.target.value)} placeholder="https://…" className={`${field} mt-2 w-full`}/></label><button type="submit" disabled={busy} className="min-h-12 rounded-full border border-[var(--brand-blue)] px-6 font-bold text-[var(--brand-blue)] disabled:opacity-60">Guardar enlace</button></form>{bookingUrl?<a href={bookingUrl} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex min-h-12 items-center font-bold underline">Abrir reservas en {new URL(bookingUrl).hostname}</a>:<p className="mt-4 text-sm">Todavía no añadiste un enlace. Puedes guardar tu disponibilidad, pero los clientes no podrán reservar desde este espacio.</p>}<p className="mt-3 text-sm text-[var(--muted)]">Se guarda en el mismo campo del perfil profesional y se comparte solo con miembros emparejados con tu perfil. Deja vacío el campo y guarda para quitarlo.</p></section>
 {notice && <p role={failed?"alert":"status"} className="rounded-xl bg-[var(--sky-surface)] p-4">{notice}</p>}
 </div>;
}
